### ISSUE TITLE
[FEATURE REQUEST] 是不是应该让其他参与者把图 pr 到项目目录下

### ISSUE THREAD

**Issue by sendya** [learnr27/cosplay#1]
是否可以增加将想要发布 cos 照片的参与者通过 pr 发到该项目的一个目录下，然后程序来读取该父目录。
并根据 commit 信息获得发布该图片的用户 ID 展示在照片下方

**Comment by learnr27** [comment]
http://chengbinbin.cn/cp/
在GitHub操作还不熟悉

**Comment by learnr27** [comment]
> 是否可以增加将想要发布cos照片的参与者通过pr发到该项目的一个目录下，然后程序来读取该父目录。
> 并根据提交信息获得发布该图片的用户ID展示在照片下方

http://chengbinbin.cn/cp/
在GitHub操作还不熟悉
